# frozen_string_literal: true

# A sample Guardfile
# More info at https://github.com/guard/guard#readme

## Uncomment and set this to only include directories you want to watch
# directories %w(app lib config test spec features) \
#  .select{|d| Dir.exists?(d) ? d : UI.warning("Directory #{d} does not exist")}

## Note: if you are using the `directories` clause above and you are not
## watching the project directory ('.'), then you will want to move
## the Guardfile to a watched dir and symlink it back, e.g.
#
#  $ mkdir config
#  $ mv Guardfile config/
#  $ ln -s config/Guardfile .
#
# and, you'll have to watch "config/Guardfile" instead of "Guardfile"

guard :rubocop, cli: %w[-D -S] do
  watch(/.rubocop.yml/)
  watch(/.+\.rb$/)
  watch(/Rakefile/)
  watch(%r{(?:.+/)?\.rubocop\.yml$}) { |m| File.dirname(m[0]) }
end

guard 'brakeman', run_on_start: true, quiet: true do
  ## Lets not watch files for brakeman, just scan on guard start, and full runs.
  #
  # watch(%r{^app/.+\.(erb|haml|rhtml|rb)$})
  # watch(%r{^config/.+\.rb$})
  # watch(%r{^lib/.+\.rb$})
  # watch('Gemfile')
end

guard 'spring', bundler: true do
  watch('Gemfile.lock')
  watch(%r{^config/})
end
